import {
  AlertCircle,
  AlertTriangle,
  ArrowRight,
  Bell,
  Check,
  CheckCheck,
  ChevronRight as ChevronRightBase,
  ChevronsUpDown as ChevronsUpDownBase,
  CircleCheck,
  Clock,
  Code,
  Command,
  Ellipsis,
  EllipsisVertical,
  ExternalLink,
  HelpCircle,
  Info,
  Loader2,
  LogOut,
  Search,
  Settings,
  Trash2,
  Users,
  X,
} from 'lucide-react'

export {
  ArrowDown,
  ArrowUp,
  CheckIcon,
  ChevronDownIcon,
  ChevronLeft,
  ChevronLeftIcon,
  ChevronRight,
  ChevronRightIcon,
  ChevronUpIcon,
  ChevronsLeft,
  ChevronsRight,
  ChevronsUpDown,
  CircleAlert,
  CircleCheckIcon,
  Compass,
  InfoIcon,
  Loader2Icon,
  MoreHorizontalIcon,
  Moon,
  OctagonXIcon,
  PanelLeftIcon,
  RefreshCw,
  SearchIcon,
  Sun,
  TriangleAlertIcon,
  XIcon,
} from 'lucide-react'

export type { LucideIcon } from 'lucide-react'

export type IconName = keyof typeof Icons

export const Icons = {
  alertCircle: AlertCircle,
  warning: AlertTriangle,
  arrowRight: ArrowRight,
  check: Check,
  checks: CheckCheck,
  circleCheck: CircleCheck,
  close: X,
  clock: Clock,
  code: Code,
  dots: Ellipsis,
  ellipsis: EllipsisVertical,
  externalLink: ExternalLink,
  help: HelpCircle,
  info: Info,
  spinner: Loader2,
  search: Search,
  settings: Settings,
  trash: Trash2,
  customers: Users,
  logo: Command,
  chevronRight: ChevronRightBase,
  notification: Bell,
  logout: LogOut,
  ChevronsUpDown: ChevronsUpDownBase,
} as const