import {
  AlertCircle,
  AlertTriangle,
  ArrowRight,
  Bell,
  Check,
  CheckCheck,
  ChevronDown,
  ChevronLeft,
  ChevronRight as ChevronRightBase,
  ChevronUp,
  ChevronsLeft,
  ChevronsRight,
  ChevronsUpDown as ChevronsUpDownBase,
  CircleCheck,
  Clock,
  Code,
  Command,
  Ellipsis,
  EllipsisVertical,
  ExternalLink,
  HelpCircle,
  Info,
  Loader2,
  LogOut,
  MoreHorizontal,
  Moon,
  PanelLeft,
  Search,
  Settings,
  Sun,
  Trash2,
  Users,
  X,
  ArrowUp,
  ArrowDown,
  ArrowUpAZ,
  ArrowDownAZ,
  ArrowUp01,
  ArrowDown01,
  ArrowUpNarrowWide,
  ArrowDownWideNarrow,
  CalendarArrowUp,
  CalendarArrowDown,
  ArrowUpDown,
  CircleX,
  RefreshCw,
  Compass,
  ArrowUpDownIcon,
} from 'lucide-react'

export type { LucideIcon } from 'lucide-react'

export type IconName = keyof typeof Icons

export const Icons = {
  alertCircle: AlertCircle,
  warning: AlertTriangle,
  arrowRight: ArrowRight,
  check: Check,
  checks: CheckCheck,
  circleCheck: CircleCheck,
  close: X,
  clock: Clock,
  code: Code,
  dots: Ellipsis,
  ellipsis: EllipsisVertical,
  externalLink: ExternalLink,
  help: HelpCircle,
  info: Info,
  spinner: Loader2,
  search: Search,
  settings: Settings,
  trash: Trash2,
  customers: Users,
  logo: Command,
  chevronRight: ChevronRightBase,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  chevronLeft: ChevronLeft,
  chevronsLeft: ChevronsLeft,
  chevronsRight: ChevronsRight,
  moreHorizontal: MoreHorizontal,
  panelLeft: PanelLeft,
  moon: Moon,
  sun: Sun,
  notification: Bell,
  logout: LogOut,
  chevronsUpDown: ChevronsUpDownBase,
  arrowUpDownAZ: ArrowUpAZ,
  arrowUpDown: ArrowUpDown,
  circleAlert: CircleX,
  refresh: RefreshCw,
  compass: Compass,
  arrowUpDownIcon: ArrowUpDownIcon,
  arrowDownAZ: ArrowDownAZ,
  arrowUp01: ArrowUp01,
  arrowDown01: ArrowDown01,
  arrowUpNarrowWide: ArrowUpNarrowWide,
  arrowDownWideNarrow: ArrowDownWideNarrow,
  arrowUp: ArrowUp,
  arrowDown: ArrowDown,
  calendarArrowUp: CalendarArrowUp,
  calendarArrowDown: CalendarArrowDown,
} as const
