import {
  AlertCircle,
  AlertTriangle,
  ArrowRight,
  Check,
  CheckCheck,
  CircleCheck,
  Clock,
  Code,
  Ellipsis,
  EllipsisVertical,
  ExternalLink,
  HelpCircle,
  Info,
  Loader2,
  Search,
  Settings,
  Trash2,
  X,
  type LucideIcon,
} from 'lucide-react'

export type Icon = React.ComponentType<LucideIcon>

export const Icons = {
  alertCircle: AlertCircle,
  warning: AlertTriangle,
  arrowRight: ArrowRight,
  check: Check,
  checks: CheckCheck,
  circleCheck: CircleCheck,
  close: X,
  clock: Clock,
  code: Code,
  dots: Ellipsis,
  ellipsis: EllipsisVertical,
  externalLink: ExternalLink,
  help: HelpCircle,
  info: Info,
  spinner: Loader2,
  search: Search,
  settings: Settings,
  trash: Trash2,
} as const
